import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Navbar from '../sections/Navbar'
import Hero from '../sections/Hero'
import Companies from '../sections/Companies'
import ProductVideo from '../sections/ProductVideo'
import Departments from '../sections/Departments'
import Teachers from '../sections/Teachers'
import Review from '../sections/Review'
import Register from '../sections/Register'
import Footer from '../sections/Footer'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <div
        className={styles.fluid}
        style={{
          background:
            ' linear-gradient(90.63deg, #fffbf4 21.32%, #f7fcf9 132.04%)',
        }}
      >
        <div className={styles.container}>
          <Navbar />
          <Hero />
        </div>
      </div>

      <div className={styles.fluid}>
        <div className={styles.container}>
          <Companies />
          <ProductVideo />
        </div>
      </div>
      <Departments />
      <div className={styles.fluid}>
        <div className={styles.container}>
          <Teachers />
          <Review />
        </div>
      </div>
      <Register />

      <div
        className={styles.fluid}
        style={{
          background: '#111116',
        }}
      >
        <div className={styles.container}>
          <Footer />
        </div>
      </div>
    </div>
  )
}
